const GAME = {
  FIRST_INNINGS: "firstInning",
  FIRST_INNINGS_TITLE: "First Innings",
  SECOND_INNINGS: "secondInning",
  SECOND_INNINGS_TITLE: "Second Innings",
  SCORE_BOARD_TITLE: "Match Summary",
  START: "Start Playing",
  TOSS: "Toss",
  BATTING: "Batting",
  BOWLING: "Bowling",
  SIMULATE_BALL: "Simple Ball",
  MATCH_SUMMARY: "Match Summary",
  WICKET: "WC",
  BATSMAN: "Batsman",
  RUNS: "Runs",
  BALLS: "Balls",
  FOURS: "4s",
  SIXES: "6s",
  BOWLER: "Bowler",
  OVERS: "Overs",
  WICKETS: "Wickets",
  STRIKE_RATE: "SR",
  BATTING_TEAM: "Batting Team",
  BOWLING_TEAM: "Bowling Team",
  SELECT_BOWLER: "Select Bowler",
  SELECT_CURRENT_BOWLER: "Select current bowler",
  FIRST_TEAM: "firstTeam",
  SELECT_TEAM_TEXT: "Select team",
  TEAM: "Team",
  CHOOSE_TEAAM_TEXT: "Choose a team",
};

export { GAME };
