import { Inter } from "next/font/google";
import StoreProvider from "./provider/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cricket Game uisng Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
